api_platform:
    title: Hello API Platform
    version: 1.0.0
    mapping:
        paths: ["%kernel.project_dir%/src/Entity"]
    patch_formats:
        json: ["application/merge-patch+json"]
    formats:
        json: ["application/json"]
        jsonld: ["application/json+ld"]
        html: ["text/html"]
        multipart: ["multipart/form-data"]
    swagger:
        versions: [3]
        api_keys:
            JWT:
                name: Authorization
                type: header
    # Mercure integration, remove if unwanted
    mercure: ~
    # Good cache defaults for REST APIs
    defaults:
        stateless: true
        cache_headers:
            vary: ["Content-Type", "Authorization", "Origin"]
    middlewares:
        - App\Middleware\CorsMiddleware
