nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 3600
    paths:
        "^/":
            origin_regex: true
            allow_origin: ["*"]
            allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
            allow_headers: ["*"]
            max_age: 3600
