nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
        hosts: []
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        "^/api/":
            allow_origin: ["*"]
            allow_headers:
                ["Content-Type", "Authorization", "Preload", "Fields"]
            allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
            expose_headers: ["Link"]
            max_age: 3600
        "^/":
            origin_regex: true
            allow_origin: ["*"]
            allow_headers:
                ["Content-Type", "Authorization", "Preload", "Fields"]
            allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
            expose_headers: ["Link"]
            max_age: 3600
