deploy:
    runs-on: ubuntu-latest

    needs: build-test

    steps:
      - uses: actions/checkout@v3

      - uses: akhileshns/heroku-deploy@v3.12.12 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "challenge-s1" #Must be unique in Heroku
          heroku_email: "taguemountkamelia094@gmail.com"
          procfile: "web: vendor/bin/heroku-php-apache2 public/"