name: CI/CD

on:
  push:
    paths:
      - "**.php"
      - "**.vue"
      - "**.js"
      - "**ci.yml"
  pull_request: ~
  workflow_dispatch: ~

jobs:
  apiPlatform-tests:
    name: Tests API PALTFORM
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        run: composer install

      # - name: Run PHPUnit tests
      #   run: php vendor/bin/phpunit

  node-test:
    name: Tests Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: client
        run: npm install

  publish-docker:
    runs-on: ubuntu-latest

    needs:
      - apiPlatform-tests

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3

        with:
          context: ./api
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenge-s1:latest

  deploy:
    runs-on: ubuntu-latest

    # needs:
    #   - apiPlatform-tests

    # defaults:
    #   run:
    #     working-directory: ./api

    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "challenge-s1" #Must be unique in Heroku
          heroku_email: "taguemountkamelia094@gmail.com"
          appdir: "api"
