name: CI/CD

on:
  push:
  pull_request: ~
  workflow_dispatch: ~
  paths:
    - "**.php"
    - "**.vue"
    - "**.js"
    - "**ci.yml"

jobs:
  apiPlatform-tests:
    name: Tests API PALTFORM
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.1"

      - name: Install Composer dependencies
        working-directory: api
        run: composer install

      # - name: Run PHPUnit tests
      #   run: vendor/bin/phpunit

  node-test:
    name: Tests Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        working-directory: client
        run: npm install

      # - name: Run NPM tests
      #   run: npm run test

  publish-docker:
    runs-on: ubuntu-latest

    needs: apiPlatform-tests

    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v3

        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/challenge-s1:latest

  # build:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v2

  #     - name: Setup Node.js
  #       uses: actions/setup-node@v2
  #       with:
  #         node-version: 14

  #     - name: Install dependencies
  #       run: npm ci

  #     - name: Build application
  # run: npm run build
  # - name: Pull images
  #   run: docker compose pull --ignore-pull-failures || true
  # - name: Start services
  #   run: docker compose up --build -d
  # - name: Wait for services
  #   run: |
  #     while status="$(docker inspect --format="{{if .Config.Healthcheck}}{{print .State.Health.Status}}{{end}}" "$(docker compose ps -q php)")"; do
  #       case $status in
  #         starting) sleep 1;;
  #         healthy) exit 0;;
  #         unhealthy)
  #           docker compose ps
  #           docker compose logs
  #           exit 1
  #         ;;
  #       esac
  #     done
  #     exit 1
  # - name: Check HTTP reachability
  #   run: curl -v -o /dev/null http://localhost
  # - name: Check HTTPS reachability
  #   run: curl  -vk -o /dev/null https://localhost
  # - name: Create test database
  #   run: |
  #     docker compose exec -T php php bin/console -e test doctrine:database:create
  #     docker compose exec -T php php bin/console -e test doctrine:migrations:migrate --no-interaction
  # - name: PHPUnit
  #   run: docker compose exec -T php php bin/phpunit
  # - name: Doctrine Schema Validator
  #   run: docker compose exec -T php php bin/console doctrine:schema:validate --skip-sync
  # - name: Jest
  #   run: docker compose exec -T pwa yarn test --ci --passWithNoTests
